# These "write functions" write newly created files to drive from analysis.



# Writes an osm to drive (usually, the osm is created by OsmGenerator)
# Parameters
# osm: matrix, osm generated by OsmGenerator
# path: string, path to experiment directory
WriteOsm <- function(osm, path) {
  
  # Checks if "/" exists after path. If not, one is added
	if(substr(path, nchar(path), nchar(path)) != "/") {
		path <- paste(path, "/", sep = "")
	}

	# create matrices folder if not already created
	matrices.path <- paste(path, "matrices/", sep = "")
	dir.create(matrices.path, showWarnings = FALSE)

  	# Export OSM
  	write.table(osm, file = paste(path, "matrices/", "total.mtrx", sep = ""), 
      	sep = " ", row.names = F,  col.names = F)
  
  	write.table(osm, file = paste(path, "osm.csv", sep = ""), 
      	sep = ",", row.names = T,  col.names = F)

}

WriteOsm(Osm, path)




# WriteOsmViz: generates a heatmap based on the OSM.
# No dendrograms are generated and the icons are in alphabetical order
# It is intended to be a raw heat map without dendrograms
# Parameters
# osm: matrix, osm generated by OsmGenerator
# number.of.participants: integer, the number of participants in the experiment can be created by ParticipantCounter
WriteOsmViz <- function(osm, number.of.participants) {
	
	# Drawing the heatmap and export as a jpeg file
	jpeg(filename = "heat_map.jpeg", width = 2000, height = 2000, units = "px",
			pointsize = 5, bg = "white", res = 700)
	heatmap.2(as.matrix(number.of.participants - osm), Rowv = F, Colv = "Rowv", dendrogram = "none", 
			margin = c(4, 4), cexRow = 0.35, cexCol = 0.35, revC = F, trace = "none", key = F)
	dev.off()
}

WriteOsmViz(Osm, number.of.participants)




# WriteClusterHeatmap: generates a cluster heatmap based on the osm
# Parameters
# osm: matrix, the osm matrix created by OsmGenerator
# number.of.participants: integer, the number of participants in the experiment can be created by ParticipantCounter
# cluster.method: string, optional parameter where the default is set to Ward's method (user has choice between options provided by the hclust function)
WriteClusterHeatmap <- function(osm, number.of.participants, cluster.method="ward.D") {
	
	# Generate the dendrogram using wards method
	cluster <- hclust(method = cluster.method, as.dist(number.of.participants - osm))
	dend <- as.dendrogram(cluster)
	
	# Drawing the cluster heatmap and export as a jpeg file
	jpeg(filename = "cluster_heatmap.jpeg", width = 2000, height = 2000, units = "px",
			pointsize = 5, bg = "white", res = 700)
	heatmap.2(as.matrix(number.of.participants - osm), Rowv = dend, Colv = dend, 
			margin = c(4, 4), cexRow = 0.35, cexCol = 0.35, dendrogram = "both", 
			revC = T, trace = "none", key = T)
	dev.off()
}

WriteClusterHeatmap(Osm, number.of.participants)




# WriteClusterAnalysis: write the dendrogram and cophenectic matrix created from ClusterAnalysis
# Parameters
# cluster.output; list, first entry in the list is a dendrogram, the second entry is a cophenectic matrix (this list created by ClusterAnalysis)
WriteClusterAnalysis  <- function(cluster.output) {

	jpeg(filename = "dendrogram.jpeg",
			width = 2000, height=2000, units="px",
			pointsize=5, bg = "white", res = 600)
	par(cex=0.65)
	plot(cluster.output[[1]])
	dev.off()

	write.table(cluster.output[[2]], file = "coph_matrix.mtrx", sep = " ", row.names = F, col.names = F)

}

WriteClusterAnalysis(cluster.output)




# WriteMdsScaling: write multi-dimensional scaling plot from MdsScaling output
# Parameters
# mds: "data type" is output from cmdscale function, output from MdsScaling function
WriteMdsScaling <- function(mds) {
	col <- rainbow(50)
	jpeg(filename = "mds.jpeg", width = 3, height =3, units = "in", pointsize = 5, bg = "white", res = 600)
	plot(min(mds[, 1], mds[, 2]):max(mds[, 1],mds[, 2]), min(mds[, 1], mds[, 2]):max(mds[, 1], mds[, 2]), type = "n", xlab = "", ylab = "", main = "Multidimensional Scaling")
	for(i in 1:nrow(mds)) {
		points(mds[i, 1], mds[i, 2], type = "p", cex = 1.5)
	}
	dev.off()
}

WriteMdsScaling(mds)




# WriteParticipantSimilarity: Write 3 participant similarity (hamming, jaccard, rand) files
# Parmaeters: 
# participant.similarity.output: list, a list containing participant similarity matrices output from ParticipantSimilarity
WriteParticipantSimilarity <- function(participant.similarity.output) {

	write.table(participant.similarity.output[[1]], file = "participant_similarity_hamming.csv", sep = " ",
			row.names = T, col.names = T)
	
	write.table(participant.similarity.output[[2]], file = "participant_similarity_jaccard.csv", sep = " ",
			row.names = T, col.names = T)
	
	write.table(participant.similarity.output[[3]], file = "participant_similarity_rand.csv", sep = " ",
			row.names = T, col.names = T)

}

WriteParticipantSimilarity(participant.similarity.output)




# Cluster validation
# Parameters
# path: string, path to experiment directory
# k: integer, number of clusters
# title: string, title of the experiment
# number.of.participants: integer, the number of participants in the experiment can be created by ParticipantCounter
# icon.names: character vector, a list of the names of the icons created by IconListGetter
ClusterValidation <- function(path, k, title="", number.of.participants, icon.names) {

	# Checks if "/" exists after path. If not, one is added
	if(substr(path, nchar(path), nchar(path)) != "/") {
		path <- paste(path, "/", sep = "")
	}
	
	ism <- list.files(paste(path, "ism/", sep=""))
	r <- sample(1:100, size=number.of.participants, replace=TRUE)
	ism.list <- data.frame(ism, r)
	ism.list <- ism.list[order(r), ]
	
	if(number.of.participants%%2 == 0) {
		split <- number.of.participants/2
	} else {
		split <- (number.of.participants-1)/2
	}
	
	# Split the participants
	group1 <- ism.list[1:split, 1]
	group2 <- ism.list[(split+1):number.of.participants, 1]
	
	# read in group1 matrix
	matrix1 <- read.delim(paste(path, "ism/", group1[1], sep=""), header=F, sep=" ", stringsAsFactors=F)
	osm1 <- data.matrix(matrix1)
	
	for (i in 2:length(group1)) {
		matrix.i <- read.delim(paste(path, "ism/", group1[i], sep=""), header=F, sep=" ", stringsAsFactors=F)
		matrix.i <- data.matrix(matrix.i)
		osm1 <- osm1 + matrix.i
	}
	
	# read in group2 matrix
	matrix2 <- read.delim(paste(path, "ism/", group2[1], sep=""), header=F, sep=" ", stringsAsFactors=F)
	osm2 <- data.matrix(matrix2)
	
	for (i in 2:length(group2)) {
		matrix.i <- read.delim(paste(path, "ism/", group2[i], sep=""), header=F, sep=" ", stringsAsFactors=F)
		matrix.i <- data.matrix(matrix.i)
		osm2 <- osm2 + matrix.i
	}
	
	d1 <- data.frame(icon.names, osm1)
	d1m <- as.matrix(d1[, -1])
	dimnames(d1m) <- list(d1[, 1], d1[, 1])
	
	d2 <- data.frame(icon.names, osm2)
	d2m <- as.matrix(d2[, -1])
	dimnames(d2m) <- list(d2[, 1], d2[, 1])
	
	ave1 <- hclust(method = "average", as.dist(number.of.participants-d1m))
	ave2 <- hclust(method = "average", as.dist(number.of.participants-d2m))
	
	comp1 <- hclust(method = "complete", as.dist(number.of.participants-d1m))
	comp2 <- hclust(method = "complete", as.dist(number.of.participants-d2m))
	
	ward1 <- hclust(method = "ward.D", as.dist(number.of.participants-d1m))
	ward2 <- hclust(method = "ward.D", as.dist(number.of.participants-d2m))
	
	# load code of A2R function
	source("http://addictedtor.free.fr/packages/A2R/lastVersion/R/code.R")
	
	# Define colors
	pre.colors <- rainbow(k)
	colors <- pre.colors[1:k]
	
	# colored dendrograms
	pdf(file= paste(path, "cluster_validation.pdf", sep=""),onefile=T,width=12, height=4)
	A2Rplot(ave1, k = k, boxes = FALSE, col.up = "gray50", col.down = colors, main=paste(title, " Group 1 Average Linkage", sep=""))
	A2Rplot(ave2, k = k, boxes = FALSE, col.up = "gray50", col.down = colors, main=paste(title, " Group 2 Average Linkage", sep=""))
	
	A2Rplot(comp1, k = k, boxes = FALSE, col.up = "gray50", col.down = colors, main=paste(title, " Group 1 Complete Linkage", sep=""))
	A2Rplot(comp2, k = k, boxes = FALSE, col.up = "gray50", col.down = colors, main=paste(title, " Group 2 Complete Linkage", sep=""))
	
	A2Rplot(ward1, k = k, boxes = FALSE, col.up = "gray50", col.down = colors, main=paste(title, " Group 1 Ward's Method", sep=""))
	A2Rplot(ward2, k = k, boxes = FALSE, col.up = "gray50", col.down = colors, main=paste(title, " Group 2 Ward's Method", sep=""))
	
	dev.off()
}

ClusterValidation(path, 3, "geo terms", number.of.participants, icon.names)




# PrototypeFreq: visualize the frequency that each icon is being selected as group prototype
# Parameters
# path: string, path to experiment directory
# icon.names: character vector, a list of the names of the icons created by IconListGetter
PrototypeFreq <- function(path, icon.names) {

	# Checks if "/" exists after path. If not, one is added
	if(substr(path, nchar(path), nchar(path)) != "/") {
		path <- paste(path, "/", sep = "")
	}
	
	# Construct the path for the zip folder and list all the zip files
	zip.path <- paste(path, "zip/", sep = "")
	files <- list.files(zip.path)
	
	# Create a dataframe to store the prototype frequency
	freq <- data.frame(icon = icon.names, 
			icon_index = 0:(length(icon.names)-1), 
			count = rep(0, length(icon.names))
	)
	
	for(p in files) {
		participant <- unzip(paste(zip.path, p, sep =""))
		participant.number <- substring(p, 1, nchar(p) - 4)
		prototype_file <- paste("./", participant.number, "/", substring(p, 1, 8), "gprototypes.csv", sep = "")
		prototype <- read.csv(prototype_file, header = F, stringsAsFactors = F)
		prev <- -1 # workaround to deal with old prototype files
		for(j in 1:nrow(prototype)) {
			if(ncol(prototype) < 4 || (!is.na(prototype[j, 2]) && !is.na(prototype[j, 3]) && !is.na(as.numeric(as.numeric(prototype[j, 3]))) && prototype[j, 2] != prev)) {
				prev <- as.numeric(prototype[j, 2])
				freq[as.numeric(prototype[j, 3]) + 1, 3] <- freq[as.numeric(prototype[j, 3]) + 1, 3] + 1
			}
		}
	}
	
	# Export batch.csv for Klipart
	write.table(freq, file = "prototype.csv", sep = ",", col.names = F, row.names = F)

	# Deletes all unzipped files as they are no longer needed
	folder.names <- substr(files, 1, nchar(files)-4)
  	for(folder in folder.names) {
    	unlink(paste(getwd(), "/", folder, sep = ""), recursive = TRUE)
  	}

  	return(freq)
  	
}

PrototypeFreq.output <- PrototypeFreq(path, icon.names)




# WriteAssignment: generate the assignment.csv for KlipArt
# Parameters
# path: string, path to experiment directory
# scenario.name: string, name of the experiment
WriteAssignment <- function(path, scenario.name) {

	# Checks if "/" exists after path. If not, one is added
	if(substr(path, nchar(path), nchar(path)) != "/") {
		path <- paste(path, "/", sep = "")
	}

	# Create an empty dataframe
	df <- data.frame()
	
	#List all zip files
	zip.path <- paste(path, "zip/", sep = "")
	files <- list.files(zip.path)
	
	for(i in 1:length(files)) {
		# Read in the assignment.csv file
		participant.i <- unzip(paste(zip.path, files[i], sep = ""))
		
		# Get the participant number for the first participant
		participant.number <- substring(files[i], 1, nchar(files[i]) - 4)
		
		# Construct the full file name for assignment.csv file
		participant.assignment <- paste("./", participant.number, "/", substring(files[i],1,8), 
				"assignment.csv", sep = "")
		
		assignment <- read.delim(participant.assignment, header = F, sep = ",", stringsAsFactors = F)
		df <- rbind(df, assignment)
	}

	# create klipart folder if not already created
	klipart.path <- paste(path, scenario.name, "-klipart/", sep = "")
	dir.create(klipart.path, showWarnings = FALSE)

	# Export the assignment.csv
	write.table(df, file = paste(paste(path, scenario.name, "-klipart/", sep = ""), "assignment.csv", sep = ""),
			sep = ",", row.names = F,  col.names = F)

	# Deletes all unzipped files as they are no longer needed
	folder.names <- substr(files, 1, nchar(files)-4)
  	for(folder in folder.names) {
    	unlink(paste(getwd(), "/", folder, sep = ""), recursive = TRUE)
  	}
}

WriteAssignment(path, scenario.name)




# WriteParticipantInfo: collect demographic info and basic experiment info (# of groups created and time spent in seconds)
# Parameters
# path: string, path to experiment directory
# scenario.name: string, name of the experiment
WriteParticipantInfo <- function(path, scenario.name) {
	
	# Checks if "/" exists after path. If not, one is added
	if(substr(path, nchar(path), nchar(path)) != "/") {
		path <- paste(path, "/", sep = "")
	}

	# Read in the zip file
	zip.path <- paste(path, "zip/", sep = "")
	files <- list.files(zip.path)
	
	# Read in to demographic info for the 1st participant
	participant1 <- unzip(paste(zip.path, files[1],sep = ""))
	
	# Get the participant number for the first participant
	first.p.number <- substring(files[1], 1, nchar(files[1]) - 4)
	
	# Construct the full file name for the participant.csv file for the 1st participant
	first.demo <- paste("./", first.p.number, "/", substring(files[1],1,8), "participant.csv", sep = "")
	
	# Read in the participant.csv for the 1st participant
	demo1 <- read.delim(first.demo, header = F, sep = ",",stringsAsFactors = F)
	
	# Aggregate eduction background for participant who use comma(s) in their eduction 
	# background (e.g., geography, education, business)
	while(length(demo1) > 13) {
		demo1[7] <- paste(demo1[7], demo1[8], sep = ",")
		demo1 <- demo1[-8]
	}

	colnames(demo1) <- 1:13
	
	# Initialize the dataframe for demographic info
	demographic <- demo1
	
	# Add demographic info from the rest of participants to the dataframe "demographic"
	for(i in 2:length(files)) {
		participant.i <- unzip(paste(zip.path, files[i], sep=""))
		
		# Get the participant number for the first participant
		participant.number <- substring(files[i], 1, nchar(files[i]) - 4)
		
		# Construct the full file name for participant.csv file
		participant.demo <- paste("./", participant.number, "/", substring(files[i],1,8), 
				"participant.csv", sep = "")
		
		# Read in the participant.csv
		demo <- read.delim(participant.demo, header = F, sep = ",", stringsAsFactors = F)
		while(length(demo) > 13) {
			demo[7] <- paste(demo[7], demo[8], sep = ",")
			demo <- demo[-8]
		}
		colnames(demo) <- 1:13
		demographic <- rbind(demographic, demo)
	}
	
	# Create two vectors to store the # of groups created and time spent (in seconds)
	groups.created <- c()
	time.spent <- c()
	
	for(i in 1:length(files)) {
		# Read in the assignment.csv file
		participant.i <- unzip(paste(zip.path, files[i], sep = ""))
		
		# Get the participant number for the first participant
		participant.number <- substring(files[i], 1, nchar(files[i]) - 4)
		
		# Construct the full file name for assignment.csv file
		participant.groups <- paste("./", participant.number, "/", substring(files[i],1,8), 
				"assignment.csv", sep = "")
		
		groups <- read.delim(participant.groups, header = F, sep = ",", stringsAsFactors = F)
		
		# Count the number of rows in the assignment file and convert it to the # of groups created
		groups <- length(unique(groups[, 2]))
		
		# Append the # of groups created to the vector "groups.created"
		groups.created <- append(groups.created, groups)
	}
	
	
	for(i in 1:length(files)) {
		# Read in the log file
		participant.i <- unzip(paste(zip.path, files[i], sep=""))
		
		# Get the participant number for the first participant
		participant.number <- substring(files[i], 1, nchar(files[i]) - 4)
		
		# Construct the full file name for .log file
		participant.log <- paste("./", participant.number, "/", substring(files[i],1,8), ".log", sep = "")
		
		# Read in the log file
		log <- read.delim(participant.log, header = F, sep=",", stringsAsFactors = F)
		
		# Get the time spent
		time <- log[nrow(log), ]
		time <- substr(time, 33, nchar(time))
		
		# Append the time spent to the vector "time.spent"
		time.spent <- append(time.spent, time)
	}
	
	# Append two vectors (i.e., two columns) - groups.created and time.spent to the demographic dataframe
	demographic <- cbind(demographic, groups.created)
	demographic <- cbind(demographic, time.spent)
	
	# Export the demographic dataframe as a csv file
	write.table(demographic, file = paste(path, "participant.csv", sep = ""),
			sep = ",", row.names = F,  col.names = F)

	# create klipart folder if not already created
	klipart.path <- paste(path, scenario.name, "-klipart/", sep = "")
	dir.create(klipart.path, showWarnings = FALSE)
	
	# Export the participant.csv for KlipArt
	write.table(demographic, file = paste(paste(path, scenario.name, "-klipart/", sep = ""), "participant.csv", sep = ""), sep = ",", row.names = F,  col.names = F)

	# Deletes all unzipped files as they are no longer needed
	folder.names <- substr(files, 1, nchar(files)-4)
  	for(folder in folder.names) {
    	unlink(paste(getwd(), "/", folder, sep = ""), recursive = TRUE)
  	}
}

WriteParticipantInfo(path, scenario.name)




# WriteDescription: extract the linguistic labels (both long and short) from all participants and store in a single csv file
# Parameters
# path: string, path to experiment directory
# scenario.name: string, name of the experiment
WriteDescription <- function(path, scenario.name) {

	# Checks if "/" exists after path. If not, one is added
	if(substr(path, nchar(path), nchar(path)) != "/") {
		path <- paste(path, "/", sep = "")
	}
	
	# Construct the path for the zip folder and list all the zip files
	zip.path <- paste(path, "zip/", sep = "")
	files <- list.files(zip.path)
	
	# Unzip the zip file from the 1st participant
	participant1 <- unzip(paste(zip.path, files[1], sep =""))
	
	# Get the participant number for the first participant
	participant.number <- substring(files[1], 1, nchar(files[1]) - 4)
	
	# Construct the full file name for the batch.csv file
	batch <- paste("./", participant.number, "/", substring(files[1],1,8), "batch.csv", sep = "")
	
	description1 <- read.csv(batch, header = F, stringsAsFactors = F)
	
	# Aggregate participants' long descriptions when they use comma in the descriptions.
	while(length(description1) > 4) {
		description1[, 4] <- paste(description1[, 4], description1[,5], sep = ",")
		description1 <- description1[-5]
	}
	
	# Create dummy column names for the dataframe (will not be included when exported)
	colnames(description1) <- 1:4
	
	# Initialize a dataframe for all descriptions
	description <- description1
	
	# Read in the batch.csv for the rest of participants and extract the descriptions
	for(i in 2:length(files)) {
		
		# Read in the zip files
		participant.i <- unzip(paste(zip.path, files[i], sep = ""))
		description.i <- read.csv(sort(participant.i)[5], header = F, stringsAsFactors = F)
		
		# Aggregate participants' long descriptions when they use comma in the descriptions.
		while(length(description.i) > 4) {
			description.i[4] <- paste(description.i[, 4], description.i[, 5], sep = ",")
			description.i <- description.i[-5]
		}
		
		# Create dummy column names for the dataframe (will not be included when exported)
		colnames(description.i) <- 1:4
		
		# Combine descriptions from all participant into a dataframe (row-bind)
		description <- rbind(description, description.i)
	}
	
	# Export the description dataframe as a csv file
	write.table(description, file = paste(path, "description.csv", sep = ""), 
			sep = ",", row.names = F,  col.names = F)
	
	# create klipart folder if not already created
	klipart.path <- paste(path, scenario.name, "-klipart/", sep = "")
	dir.create(klipart.path, showWarnings = FALSE)

	# Export batch.csv for Klipart
	write.table(description, file=paste(paste(path, scenario.name, "-klipart/", sep = ""), "batch.csv", sep = ""), sep = ",", col.names=  F, row.names = F)

	# Deletes all unzipped files as they are no longer needed
	folder.names <- substr(files, 1, nchar(files)-4)
  	for(folder in folder.names) {
    	unlink(paste(getwd(), "/", folder, sep = ""), recursive = TRUE)
  	}
}

WriteDescription(path, scenario.name)




# WriteOverview: produces an overall report of the general information from the experiment 
# Parameters
# scenario.name: string, name of the experiment
# participant.info.path: string, full path to the participant.csv created by WriteParticipantInfo
# number.of.participants: integer, the number of participants in the experiment can be created by ParticipantCounter
WriteOverview <- function(scenario.name, participant.info.path, number.of.participants) {
	output <- paste(scenario.name, "_overview.pdf", sep = "")
	data <- read.csv(participant.info.path, header=F, stringsAsFactors = F)
	
	male <- 0
	female <- 0
	for (i in 1:nrow(data)) {
		if (data[i, 3] == "male") {
			male <- male+1
		} else {
			female <- female+1
		}
	}
	
	aveage <- round(mean(data[, 2]), 2)
	max <- max(data[, 2])
	min <- min(data[, 2])
	
	
	pdf(file = output, onefile = T, width=10, height=25)
	
	layout(matrix(c(1,1,2,2,3,3,4,5), 4, 2, byrow = TRUE))
	
	plot.new()
	title(paste("Total participants: ", number.of.participants, ";", sep = ""), line = -18, cex = 20)
	title(paste("Male: ", male, ", Female: ", female, sep = ""), line = -20, cex = 20)
	title(paste("Average age: ", aveage, " (max: ", max, ", min: ", min, ")", sep = ""), line = -22, cex = 20)
	boxplot(data[, 14],
			horizontal = TRUE, 
			notch = FALSE,  # Notches for CI for median
			col = "slategray3",
			boxwex = 0.5,  # Width of box as proportion of original
			whisklty = 1,  # Whisker line type; 1 = solid line
			staplelty = 0,  # Staple (line at end) type; 0 = none
			outpch = 16,  # Symbols for outliers; 16 = filled circle
			outcol = "slategray3",  # Color for outliers
			main = "Groups Created")
	boxplot(data[, 15],
			horizontal = TRUE, 
			#notch = TRUE,  # Notches for CI for median
			col = "slategray3",
			boxwex = 0.5,  # Width of box as proportion of original
			whisklty = 1,  # Whisker line type; 1 = solid line
			staplelty = 0,  # Staple (line at end) type; 0 = none
			outpch = 16,  # Symbols for outliers; 16 = filled circle
			outcol = "slategray3",  # Color for outliers
			main = "Grouping Time")
	
	groupscount <- data.frame(table(data[, 14]))
	
	a <- groupscount$Var1
	b <- c()
	for (i in 1:length(a)) {
		b[i] <- toString(a[i])
	}
	
	groupmean <- mean(data[, 14])
	groupsd <- round(sd(data[, 14]), 2)
	
	barplot(groupscount$Freq, names.arg = b, 
			main = paste("Groups Created (mean = ", groupmean, ", ", "sd = ", groupsd, ")", sep = ""),
			xlab = "Number of groups created", ylab="Frequency")
	
	hist(data[, 15], col = "grey", main = paste("Grouping Time", " (mean = ", round(mean(data[, 15]), 2), "s", "," , " sd = ", round(sd(data[, 15]), 2), "s", ")", sep = ""), xlab = "Time spent on grouping in second")
	title(scenario.name, outer = T, line = -2, cex.main = 2, col.main = "blue")
	
	dev.off()
}

WriteOverview(scenario.name, paste(path, "/participant.csv", sep=""), number.of.participants)



















